### ISSUE TITLE
Support for MMC5603NJ, chip ID 0x00

### ISSUE THREAD

**Issue by frankcohen** [adafruit/Adafruit_MMC56x3#3]
- Arduino board:  Reflections board, ESP32-S3 with MMC5603NJ magnetometer. Gerbers and software at https://github.com/frankcohen/ReflectionsOS
 
- Arduino IDE version: 2.3.2

- List the steps to reproduce the problem below
Some MMC5603 variants uses (or ignore) the device ID code from WHO_AM_I register. For example, MMC5603NJ (https://jlcpcb.com/parts/componentSearch?searchTxt=MMC5603NJ&_t=1718386987988) returns an ID value of 0x00. I modified the library to have an overloaded begin() method accepting a custom ID value.

```
  if (!mag.begin( MMC5603NJ_ADDRESS, &Wire, **MMC5603NJ_ID** ) ) 
  {  // I2C mode
    Serial.println("No MMC5603 detected");
    while(1);
  }
```

Here is the patch to Adafruit_MMC56x3.h

  bool begin(uint8_t i2c_address, TwoWire *wire, uint16_t chip_id );
  uint16_t _sensorChipID = MMC56X3_CHIP_ID;

and the patch to Adafruit_MMC56x3.cpp

```
bool Adafruit_MMC5603::begin(uint8_t i2c_address, TwoWire *wire, uint16_t chip_id ) {

  _sensorChipID = chip_id;

  return begin( i2c_address, wire );
}
```

and

```
  // make sure we're talking to the right chip
  if (chip_id.read() != _sensorChipID) {
    // No MMC56X3 detected ... return false
    return false;
  }

```

I'm glad to make a pull request provided there are no objections.

-Frank Cohen
Reflections project, principal maintainer

**Comment by ladyada** [comment]
this is done :)

**Comment by frankcohen** [comment]
Thank you
